### ISSUE TITLE
Add Extra Information

### ISSUE THREAD

**Issue by moshthepitt** [onaio/kaznet-web#238]
### XForm

 - [x] the owner at Ona
 - [x] the project at Ona
 - [x] the view in Ona URL

### Task

 - [x] the view in Ona URL
